"""initial migration

Revision ID: 958e5c165195
Revises: b25d1b8d2d03
Create Date: 2016-12-18 17:30:09.344638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958e5c165195'
down_revision = 'b25d1b8d2d03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifications', sa.Column('img_src', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifications', 'img_src')
    # ### end Alembic commands ###
