"""initial migration

Revision ID: c61fb191e0e9
Revises: 958e5c165195
Create Date: 2016-12-18 22:37:14.567401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61fb191e0e9'
down_revision = '958e5c165195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifications', sa.Column('brief', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifications', 'brief')
    # ### end Alembic commands ###
